windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAMw/////QAACfwAAAIYAAADggAAACMAAAoAAAAEOAAAAAAABAAACgAAAAMzAAAA
    AAAACfkAAAIV
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:07'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: odysee.com
      url: https://odysee.com/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: YouTube
      url: https://www.youtube.com/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Somehow, MoviePass Got Worse: Diabolical Tactics Uncovered! - News Dump
        - YouTube'
      url: https://www.youtube.com/watch?v=CubwRGM-Src
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 80
      title: Inflation Is Going CRAZY. But the government WANTS it. - YouTube
      url: https://www.youtube.com/watch?v=dgDbuovQTv4
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2021-06-12T07:47:03'
      pinned: true
      scroll-pos:
        x: 0
        y: 1633
      title: 'How do you conditionally unbind shortcuts? : qutebrowser'
      url: https://www.reddit.com/r/qutebrowser/comments/nxgono/how_do_you_conditionally_unbind_shortcuts/h1geia9/?context=3
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: linux hibernate - YouTube
      url: https://www.youtube.com/results?search_query=linux+hibernate
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:49'
      pinned: false
      scroll-pos:
        x: 0
        y: 540
      title: Arch Linux + Grub | Setup Hibernation - YouTube
      url: https://www.youtube.com/watch?v=Xek3TGKzLWw&t=343s
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: arch linux hibernate - searx
      url: https://searx.bar/search?q=arch%20linux%20hibernate
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Can''t get hibernate to work? : archlinux'
      url: https://www.reddit.com/r/archlinux/comments/85q84q/cant_get_hibernate_to_work/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Cannot restore session after hibernation : linuxquestions'
      url: https://www.reddit.com/r/linuxquestions/comments/7swvyb/cannot_restore_session_after_hibernation/?utm_source=reddit-android
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:01'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: artix openrc hibernate - searx
      url: https://searx.bar/search?q=artix%20openrc%20hibernate
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Power management (i.e. hibernation/shutdown) hangs on forever.
      url: https://forum.artixlinux.org/index.php/topic,2252.0.html
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Suspend and hibernate - Gentoo Wiki
      url: https://wiki.gentoo.org/wiki/Suspend_and_hibernate
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Power management/Suspend and hibernate - ArchWiki
      url: https://wiki.archlinux.org/title/Power_management/Suspend%20and%20hibernate
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Wiki | Main / Artix Wiki Main Page | Search Results
      url: https://wiki.artixlinux.org/?q=hibernate&n=Main.HomePage&action=search
      zoom: 1.0
- geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAAzIAAAQ3AAAAAwAAAAMAAAMvAAAENAAAAAAAAAAACgAAAAADAAAA
    AwAAAy8AAAQ0
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: hid-examples/Main.hs at master · bravit/hid-examples
      url: https://github.com/bravit/hid-examples/blob/master/ch02/radar/Main.hs
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:14'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: maybe applicative - Hoogle
      url: https://hoogle.haskell.org/?hoogle=maybe+applicative&scope=set%3Astackage
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:07'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: Typeclassopedia - HaskellWiki
      url: https://wiki.haskell.org/Typeclassopedia
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Haskell/Category theory - Wikibooks, open books for an open world
      url: https://en.wikibooks.org/wiki/Haskell/Category_theory
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Abstraction, intuition, and the “monad tutorial fallacy” | blog :: Brent
        -> [String]'
      url: https://byorgey.wordpress.com/2009/01/12/abstraction-intuition-and-the-monad-tutorial-fallacy/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Sets — containers 0.5.10.2 documentation
      url: https://haskell-containers.readthedocs.io/en/latest/set.html#short-example
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:00'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'summoner :: Kowainik'
      url: https://kowainik.github.io/projects/summoner
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Pointfree.io
      url: http://pointfree.io/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:47:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Lambdabot - HaskellWiki
      url: https://wiki.haskell.org/Lambdabot
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2021-06-12T07:46:59'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: KataCatalogue - Coding Dojo
      url: http://codingdojo.org/KataCatalogue/
      zoom: 1.0
