#!/bin/sh

# For more info, visit:
# https://github.com/slotThe/xmonad/blob/new-tutorial/INSTALL.md#tell-xmonad-how-to-recompile-itself

exec stack ghc --  \
  --make xmonad.hs \
  -i               \
  -ilib            \
  -fforce-recomp   \
  -main-is main    \
  -v0              \
  -o "$1"
