# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name: Philippe Fanaro
    author-email: philippefanaro@gmail.com
    category: Example
    copyright: BSD
    github-username: psygo

# The following parameter specifies stack's output styles; STYLES is a
# colon-delimited sequence of key=value, where 'key' is a style name and
# 'value' is a semicolon-delimited list of 'ANSI' SGR (Select Graphic
# Rendition) control codes (in decimal). Use "stack ls stack-colors --basic"
# to see the current sequence.
# stack-colors: STYLES
